/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.ext.model;

import com.liferay.asset.ext.service.persistence.AssetEntryUserStatusPK;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AssetEntryUserStatus service. Represents a row in the &quot;ASSET_EXT_AssetEntryUserStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.asset.ext.model.impl.AssetEntryUserStatusModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.asset.ext.model.impl.AssetEntryUserStatusImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetEntryUserStatus
 * @generated
 */
@ProviderType
public interface AssetEntryUserStatusModel
	extends BaseModel<AssetEntryUserStatus>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset entry user status model instance should use the {@link AssetEntryUserStatus} interface instead.
	 */

	/**
	 * Returns the primary key of this asset entry user status.
	 *
	 * @return the primary key of this asset entry user status
	 */
	public AssetEntryUserStatusPK getPrimaryKey();

	/**
	 * Sets the primary key of this asset entry user status.
	 *
	 * @param primaryKey the primary key of this asset entry user status
	 */
	public void setPrimaryKey(AssetEntryUserStatusPK primaryKey);

	/**
	 * Returns the uuid of this asset entry user status.
	 *
	 * @return the uuid of this asset entry user status
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this asset entry user status.
	 *
	 * @param uuid the uuid of this asset entry user status
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the asset entry user status ID of this asset entry user status.
	 *
	 * @return the asset entry user status ID of this asset entry user status
	 */
	public long getAssetEntryUserStatusId();

	/**
	 * Sets the asset entry user status ID of this asset entry user status.
	 *
	 * @param assetEntryUserStatusId the asset entry user status ID of this asset entry user status
	 */
	public void setAssetEntryUserStatusId(long assetEntryUserStatusId);

	/**
	 * Returns the group ID of this asset entry user status.
	 *
	 * @return the group ID of this asset entry user status
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this asset entry user status.
	 *
	 * @param groupId the group ID of this asset entry user status
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this asset entry user status.
	 *
	 * @return the company ID of this asset entry user status
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this asset entry user status.
	 *
	 * @param companyId the company ID of this asset entry user status
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this asset entry user status.
	 *
	 * @return the user ID of this asset entry user status
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this asset entry user status.
	 *
	 * @param userId the user ID of this asset entry user status
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this asset entry user status.
	 *
	 * @return the user uuid of this asset entry user status
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this asset entry user status.
	 *
	 * @param userUuid the user uuid of this asset entry user status
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this asset entry user status.
	 *
	 * @return the user name of this asset entry user status
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this asset entry user status.
	 *
	 * @param userName the user name of this asset entry user status
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this asset entry user status.
	 *
	 * @return the create date of this asset entry user status
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this asset entry user status.
	 *
	 * @param createDate the create date of this asset entry user status
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this asset entry user status.
	 *
	 * @return the modified date of this asset entry user status
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this asset entry user status.
	 *
	 * @param modifiedDate the modified date of this asset entry user status
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the entry ID of this asset entry user status.
	 *
	 * @return the entry ID of this asset entry user status
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this asset entry user status.
	 *
	 * @param entryId the entry ID of this asset entry user status
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the acknowledged of this asset entry user status.
	 *
	 * @return the acknowledged of this asset entry user status
	 */
	public boolean getAcknowledged();

	/**
	 * Returns <code>true</code> if this asset entry user status is acknowledged.
	 *
	 * @return <code>true</code> if this asset entry user status is acknowledged; <code>false</code> otherwise
	 */
	public boolean isAcknowledged();

	/**
	 * Sets whether this asset entry user status is acknowledged.
	 *
	 * @param acknowledged the acknowledged of this asset entry user status
	 */
	public void setAcknowledged(boolean acknowledged);

	/**
	 * Returns the acknowledgement date of this asset entry user status.
	 *
	 * @return the acknowledgement date of this asset entry user status
	 */
	public Date getAcknowledgementDate();

	/**
	 * Sets the acknowledgement date of this asset entry user status.
	 *
	 * @param acknowledgementDate the acknowledgement date of this asset entry user status
	 */
	public void setAcknowledgementDate(Date acknowledgementDate);

	/**
	 * Returns the downloaded of this asset entry user status.
	 *
	 * @return the downloaded of this asset entry user status
	 */
	public boolean getDownloaded();

	/**
	 * Returns <code>true</code> if this asset entry user status is downloaded.
	 *
	 * @return <code>true</code> if this asset entry user status is downloaded; <code>false</code> otherwise
	 */
	public boolean isDownloaded();

	/**
	 * Sets whether this asset entry user status is downloaded.
	 *
	 * @param downloaded the downloaded of this asset entry user status
	 */
	public void setDownloaded(boolean downloaded);

	/**
	 * Returns the download date of this asset entry user status.
	 *
	 * @return the download date of this asset entry user status
	 */
	public Date getDownloadDate();

	/**
	 * Sets the download date of this asset entry user status.
	 *
	 * @param downloadDate the download date of this asset entry user status
	 */
	public void setDownloadDate(Date downloadDate);

	/**
	 * Returns the read of this asset entry user status.
	 *
	 * @return the read of this asset entry user status
	 */
	public boolean getRead();

	/**
	 * Returns <code>true</code> if this asset entry user status is read.
	 *
	 * @return <code>true</code> if this asset entry user status is read; <code>false</code> otherwise
	 */
	public boolean isRead();

	/**
	 * Sets whether this asset entry user status is read.
	 *
	 * @param read the read of this asset entry user status
	 */
	public void setRead(boolean read);

	/**
	 * Returns the read date of this asset entry user status.
	 *
	 * @return the read date of this asset entry user status
	 */
	public Date getReadDate();

	/**
	 * Sets the read date of this asset entry user status.
	 *
	 * @param readDate the read date of this asset entry user status
	 */
	public void setReadDate(Date readDate);

}